apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth-service-pull
  namespace: auth-service
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: auth
    app.kubernetes.io/component: api
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{}}}'
