apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: auth
    app.kubernetes.io/component: api
