spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${AUTH_LOCAL_DB_URL:jdbc:postgresql://localhost:5432/authdb_local}
    driver-class-name: org.postgresql.Driver
    username: ${AUTH_LOCAL_DB_USERNAME:auth_local_user}
    password: ${AUTH_LOCAL_DB_PASSWORD:auth_local_password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
server:
  port: 8080
logging:
  level:
    org.springframework: DEBUG
    com.az.auth: DEBUG
---
# Add environment-specific values and secrets only for local use
